---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную верси
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - В категории товаров необходимо добавить еще один пункт "Все"
  - Необходимо, чтобы при переходе с Корзины в Магазин значения фильтров сохранялись
  - Пользователь должен иметь возможность увеличить количество товара при добавлении его в корзину
  - На странице Корзина данные о количестве товаров необходимо сравнять по вертикали
  - Необходимо добавить подтверждение удаления товара на странице Корзина
  - В каталоге товаров необхожимо поменять статус кнопки "В корзину" на "В корзине" и поменять цвет кнопки на зеленый после добавления товара в корзину
  - В окне поформления заказов данные о количестве товаров необходимо сравнять по вертикали
